package gregor.developer.trainingprogramcompose.dialog.dialog_list.DescriptionArray

import android.content.Context
import gregor.developer.trainingprogramcompose.R

fun DescriptionBicepsArray(context: Context): Array<Array<String>> {
    return arrayOf(
        context.resources.getStringArray(R.array.descriptionBicepsSeatedZottmanCurl),
        context.resources.getStringArray(R.array.descriptionBicepsStandingBarbellConcentrationCurl),
        context.resources.getStringArray(R.array.descriptionBicepsWaiterCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDoubleArmDumbbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsBarbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsConcentrationCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellPreacherCurl),
        context.resources.getStringArray(R.array.descriptionBicepsEZBarPreacherCurl),
        context.resources.getStringArray(R.array.descriptionBicepsHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSeatedInclineDumbbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsLeverPreacherCurl),
        context.resources.getStringArray(R.array.descriptionBicepsHighCableSingleArmBicepCurl),
        context.resources.getStringArray(R.array.descriptionBicepsOneArmCableCurl),
        context.resources.getStringArray(R.array.descriptionBicepsLyingCableCurl),
        context.resources.getStringArray(R.array.descriptionBicepsZottmanCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellReverseCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSeatedCloseGripConcentrationCurl),
        context.resources.getStringArray(R.array.descriptionBicepsBicepsLegConcentrationCurl),
        context.resources.getStringArray(R.array.descriptionBicepsProneInclineBarbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsOverheadCableCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSeatedHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSeatedBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSingleArmCablePreacherCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCableConcentrationCurl),
        context.resources.getStringArray(R.array.descriptionBicepsReverseGripEZBarCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellScottHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsLyingHighBenchBarbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCableRopeHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsBicepsCurlMachine),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellHighCurl),
        context.resources.getStringArray(R.array.descriptionBicepsBrachialisPullUp),
        context.resources.getStringArray(R.array.descriptionBicepsCloseGripZBarCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellScottCurl),
        context.resources.getStringArray(R.array.descriptionBicepsBarbellCurlOnArmBlaster),
        context.resources.getStringArray(R.array.descriptionBicepsArmBlasterHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellCurlOnArmBlaster),
        context.resources.getStringArray(R.array.descriptionBicepsStandingOneArmChestStretch),
        context.resources.getStringArray(R.array.descriptionBicepsOneArmBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsChinUp),
        context.resources.getStringArray(R.array.descriptionBicepsLeverBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCableInclineBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsOneArmChinUp),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellPreacherHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsOneArmProneDumbbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsDumbbellAlternatePreacherCurl),
        context.resources.getStringArray(R.array.descriptionBicepsTwoDumbbellPreacherCurl),
        context.resources.getStringArray(R.array.descriptionBicepsFlexorInclineDumbbellCurls),
        context.resources.getStringArray(R.array.descriptionBicepsBarbellAlternateBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCableKneelingBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCableTwoArmCurlOnInclineBench),
        context.resources.getStringArray(R.array.descriptionBicepsChinUpAroundTheBar),
        context.resources.getStringArray(R.array.descriptionBicepsElbowFlexion),
        context.resources.getStringArray(R.array.descriptionBicepsCablePulldownBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsBandBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSingleDumbbellSpiderHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCableCurl),
        context.resources.getStringArray(R.array.descriptionBicepsZBarCurl),
        context.resources.getStringArray(R.array.descriptionBicepsHammerCurlWithResistanceBand),
        context.resources.getStringArray(R.array.descriptionBicepsCableReverseGripEZBarBicepsCurl),
        context.resources.getStringArray(R.array.descriptionBicepsStandingReverseShoulderStretch),
        context.resources.getStringArray(R.array.descriptionBicepsBarbellDragCurl),
        context.resources.getStringArray(R.array.descriptionBicepsCloseGripBarbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsOneArmCableBicepCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSingleArmReverseGripCableBicepCurl),
        context.resources.getStringArray(R.array.descriptionBicepsWaterBottleHammerCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSeatedAlternatingDumbbellCurl),
        context.resources.getStringArray(R.array.descriptionBicepsSeatedBicepCurlWithResistanceBand),
        context.resources.getStringArray(R.array.descriptionBicepsOneArmBicepsCurlWithResistanceBand),
    )
}