package gregor.developer.trainingprogramcompose.dialog.dialog_list.DescriptionArray

import android.content.Context
import gregor.developer.trainingprogramcompose.R

fun DescriptionCalisthenicsArray(context: Context): Array<Array<String>> {
    return arrayOf(
        context.resources.getStringArray(R.array.descriptionCalisthenicsFrogStand),
        context.resources.getStringArray(R.array.descriptionCalisthenicsWallWalk),
        context.resources.getStringArray(R.array.descriptionCalisthenicsDragonFlag),
        context.resources.getStringArray(R.array.descriptionCalisthenicsHumanFlag),
        context.resources.getStringArray(R.array.descriptionCalisthenicsPullUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsLeglessRopeClimb),
        context.resources.getStringArray(R.array.descriptionCalisthenicsMuscleUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsCaptainsChairLegRaise),
        context.resources.getStringArray(R.array.descriptionCalisthenicsCloseGripChinUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsHangingKneeRaises),
        context.resources.getStringArray(R.array.descriptionCalisthenicsHangingSideKneeRaises),
        context.resources.getStringArray(R.array.descriptionCalisthenicsHangingWindshieldWiper),
        context.resources.getStringArray(R.array.descriptionCalisthenicsToesToBar),
        context.resources.getStringArray(R.array.descriptionCalisthenicsParallelBarDips),
        context.resources.getStringArray(R.array.descriptionCalisthenicsHandstandPushUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsReversePushUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsCrossArmPushUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsUpsideDownPullUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsLSit),
        context.resources.getStringArray(R.array.descriptionCalisthenicsClapPushUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsAbStrapsLegRaise),
        context.resources.getStringArray(R.array.descriptionCalisthenicsDipsBetweenChairs),
        context.resources.getStringArray(R.array.descriptionCalisthenicsRingInvertedRow),
        context.resources.getStringArray(R.array.descriptionCalisthenicsImpossibleDips),
        context.resources.getStringArray(R.array.descriptionCalisthenicsKoreanDips),
        context.resources.getStringArray(R.array.descriptionCalisthenicsStraightBarDip),
        context.resources.getStringArray(R.array.descriptionCalisthenicsBenchPikePushUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsPikePushUp),
        context.resources.getStringArray(R.array.descriptionCalisthenicsLSitPullUp),
        context.resources.getStringArray(R.array.descriptionBackLever),
        context.resources.getStringArray(R.array.descriptionSwing360),
        context.resources.getStringArray(R.array.descriptionFrontLeverPullUp),
        context.resources.getStringArray(R.array.descriptionSingleArmPushUp),
        context.resources.getStringArray(R.array.descriptionWallSupportedHandstandPushUps),
        context.resources.getStringArray(R.array.descriptionArcherPullUp),
        context.resources.getStringArray(R.array.descriptionHandstand),
        context.resources.getStringArray(R.array.descriptionForearmPushUp),
        context.resources.getStringArray(R.array.descriptionHandstandPushUpsBetweenBenches),
        context.resources.getStringArray(R.array.descriptionKippingHandstandPushUp),
        context.resources.getStringArray(R.array.descriptionHinduPushUps),
        context.resources.getStringArray(R.array.descriptionDiamondPushUp),
        context.resources.getStringArray(R.array.descriptionPushUp),
        context.resources.getStringArray(R.array.descriptionSuspendedAbFallOut),
        context.resources.getStringArray(R.array.descriptionBodyweightSkullCrushers),
        context.resources.getStringArray(R.array.descriptionStraddlePlanche),
        context.resources.getStringArray(R.array.descriptionPlanchePushUp),
        context.resources.getStringArray(R.array.descriptionFingerPushUp),
        context.resources.getStringArray(R.array.descriptionChestTapPushUp),
        context.resources.getStringArray(R.array.descriptionArcherPushUp),
        context.resources.getStringArray(R.array.descriptionRingDips),
        context.resources.getStringArray(R.array.descriptionSingleArmRaisePushUp),
    )
}