package gregor.developer.trainingprogramcompose.dialog.dialog_list.DescriptionArray

import android.content.Context
import gregor.developer.trainingprogramcompose.R

fun DescriptionTrapeziusArray(context: Context): Array<Array<String>> {
    return arrayOf(
        context.resources.getStringArray(R.array.descriptionTrapeziusOverheadShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusGittlesonShrug),
        context.resources.getStringArray(R.array.descriptionTrapezius45DegreeInclineRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusDumbbellShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusCableShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusBarbellShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusBehindTheBackBarbellShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusDumbbellInclineShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusProneInclineShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusLeverShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusRearDeltFlyMachine),
        context.resources.getStringArray(R.array.descriptionTrapeziusLeverGriplessShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusCableRearDeltFly),
        context.resources.getStringArray(R.array.descriptionTrapeziusBentOverLateralRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusCableUprightRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusFacePull),
        context.resources.getStringArray(R.array.descriptionTrapeziusHalfKneelingHighCableRowRope),
        context.resources.getStringArray(R.array.descriptionTrapeziusDumbbellRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusDumbbellUprightRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusBodyweightMilitaryPress),
        context.resources.getStringArray(R.array.descriptionTrapeziusKneelingHighPulleyRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusEzBarUprightRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusBandPullApart),
        context.resources.getStringArray(R.array.descriptionTrapeziusBentOverReverseCableFly),
        context.resources.getStringArray(R.array.descriptionTrapeziusBentOverBarbellReverseRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusBarbellRearDeltRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusSmithMachineShrug),
        context.resources.getStringArray(R.array.descriptionTrapeziusInclineDumbbellReverseFly),
        context.resources.getStringArray(R.array.descriptionTrapeziusInclineDumbbellYRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusDumbbellInclineTRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusSwimming),
        context.resources.getStringArray(R.array.descriptionTrapeziusBentOverRearDeltFlyGymstick),
        context.resources.getStringArray(R.array.descriptionTrapeziusScapularProtractionRetraction),
        context.resources.getStringArray(R.array.descriptionTrapeziusCrossCableFacePull),
        context.resources.getStringArray(R.array.descriptionTrapeziusElbowReversePushUp),
        context.resources.getStringArray(R.array.descriptionTrapeziusScapulaDips),
        context.resources.getStringArray(R.array.descriptionTrapeziusPushUpPlus),
        context.resources.getStringArray(R.array.descriptionTrapeziusSeatedBallerinaExercise),
        context.resources.getStringArray(R.array.descriptionTrapeziusSeatedScapularRetractionExercise),
        context.resources.getStringArray(R.array.descriptionTrapeziusFoamRollerRhomboids),
        context.resources.getStringArray(R.array.descriptionTrapeziusFoamRollerUpperBack),
        context.resources.getStringArray(R.array.descriptionTrapeziusScapulaPullUp),
        context.resources.getStringArray(R.array.descriptionTrapeziusSerratusWallSlideWithFoamRoller),
        context.resources.getStringArray(R.array.descriptionTrapeziusDipShrugs),
        context.resources.getStringArray(R.array.descriptionTrapeziusWideGripBarbellBentOverRowPlus),
        context.resources.getStringArray(R.array.descriptionTrapeziusWideGripAlternateBarbellBentOverRowPlus),
        context.resources.getStringArray(R.array.descriptionTrapeziusOneArmDumbbellUprightRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusCableYRaise),
        context.resources.getStringArray(R.array.descriptionTrapeziusBarbellUprightRow),
        context.resources.getStringArray(R.array.descriptionTrapeziusResistanceBandBentOverRearDeltFly),
        context.resources.getStringArray(R.array.descriptionTrapeziusResistanceBandPullApart),
        context.resources.getStringArray(R.array.descriptionTrapeziusSingleArmUprightRowGymstick),
        context.resources.getStringArray(R.array.descriptionTrapeziusFacePullWithResistanceBand),
    )
}