package gregor.developer.trainingprogramcompose.dialog.dialog_list.DescriptionArray

import android.content.Context
import gregor.developer.trainingprogramcompose.R

fun DescriptionYogaArray(context: Context): Array<Array<String>> {
    return arrayOf(
        context.resources.getStringArray(R.array.descriptionYogaWarrior1Pose),
        context.resources.getStringArray(R.array.descriptionYogaWarrior2Pose),
        context.resources.getStringArray(R.array.descriptionYogaWarrior3Pose),
        context.resources.getStringArray(R.array.descriptionYogaHumbleWarriorPose),
        context.resources.getStringArray(R.array.descriptionYogaReverseWarriorPose),
        context.resources.getStringArray(R.array.descriptionYogaUstrasana),
        context.resources.getStringArray(R.array.descriptionYogaUtthitaTrikonasana),
        context.resources.getStringArray(R.array.descriptionYogaTigerYogaPose),
        context.resources.getStringArray(R.array.descriptionYogaBhekasanaFrogPose),
        context.resources.getStringArray(R.array.descriptionYogaBalasana),
        context.resources.getStringArray(R.array.descriptionYogaAnuvittasana),
        context.resources.getStringArray(R.array.descriptionYogaAnjaneyasana),
        context.resources.getStringArray(R.array.descriptionYogaEkaPadaSetuBandhaSarvangasana),
        context.resources.getStringArray(R.array.descriptionYogaDandayamanaBharmanasana),
        context.resources.getStringArray(R.array.descriptionYogaChaturangaDandasana),
        context.resources.getStringArray(R.array.descriptionYogaBitilasana),
        context.resources.getStringArray(R.array.descriptionYogaPadaHastasana),
        context.resources.getStringArray(R.array.descriptionYogaTitliAsana),
        context.resources.getStringArray(R.array.descriptionBaddhaKonasanaButterflyPose),
        context.resources.getStringArray(R.array.descriptionYogaMakarasana),
        context.resources.getStringArray(R.array.descriptionYogaArdhaUttanasana),
        context.resources.getStringArray(R.array.descriptionYogaArdhaKapotasana),
        context.resources.getStringArray(R.array.descriptionYogaAdvasana),
        context.resources.getStringArray(R.array.descriptionYogaAdhoMukhaVrksasana),
        context.resources.getStringArray(R.array.descriptionYogaAdhoMukhaSvanasana),
        context.resources.getStringArray(R.array.descriptionYogaTadasana),
        context.resources.getStringArray(R.array.descriptionYogaSuptaBaddhaKonasana),
        context.resources.getStringArray(R.array.descriptionYogaViparitaKarani),
        context.resources.getStringArray(R.array.descriptionYogaSuptaMatsyendrasana),
        context.resources.getStringArray(R.array.descriptionYogaSamakonasana),
        context.resources.getStringArray(R.array.descriptionYogaShoulderstand),
        context.resources.getStringArray(R.array.descriptionYogaNaukaSanchalanasan),
        context.resources.getStringArray(R.array.descriptionYogaMalasana),
        context.resources.getStringArray(R.array.descriptionYogaFullLotusPose),
        context.resources.getStringArray(R.array.descriptionYogaHalasana),
        context.resources.getStringArray(R.array.descriptionYogaLocustPose),
        context.resources.getStringArray(R.array.descriptionYogaWheelPose),
        context.resources.getStringArray(R.array.descriptionYogaGarudasana),
        context.resources.getStringArray(R.array.descriptionYogaCrabPose),
        context.resources.getStringArray(R.array.descriptionYogaChildsPoseToCobra),
        context.resources.getStringArray(R.array.descriptionYogaCamelPose),
        context.resources.getStringArray(R.array.descriptionYogaBridgePose),
        context.resources.getStringArray(R.array.descriptionYogaSaithalyasana),
        context.resources.getStringArray(R.array.descriptionYogaUpavisthaKonasana),
        context.resources.getStringArray(R.array.descriptionYogaBhujangasana),
        context.resources.getStringArray(R.array.descriptionYogaFishPose),
        context.resources.getStringArray(R.array.descriptionYogaBowPose),
        context.resources.getStringArray(R.array.descriptionYogaCatCowPose),
        context.resources.getStringArray(R.array.descriptionYogaAbdominalBracing),
        context.resources.getStringArray(R.array.descriptionYogaDoublePigeonPose),
        context.resources.getStringArray(R.array.descriptionYogaFrogPose),
        context.resources.getStringArray(R.array.descriptionYogaSupineSpinalTwist),
        context.resources.getStringArray(R.array.descriptionYogaParsvaBalasana),
        context.resources.getStringArray(R.array.descriptionYogaHalfFrogPose),
        context.resources.getStringArray(R.array.descriptionYogaHappyBabyPose),
        context.resources.getStringArray(R.array.descriptionYogaDhanurasana),
    )
}