package gregor.developer.trainingprogramcompose.dialog.dialog_list.DescriptionArray

import android.content.Context
import gregor.developer.trainingprogramcompose.R

fun DescriptionErectorSpinaeArray(context: Context): Array<Array<String>> {
    return arrayOf(
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellGoodMorning),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellSumoDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSeatedBackExtension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeBarbellBentOverRow),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeBentOverDumbbellRow),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeRomanianDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSphinxStretch),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeGoodMorning),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeWeightedBackExtension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellRomanianDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSumoDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellStraightLegDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSeatedHamstringStretch),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeKettlebellSingleLegDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeHyperextension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeFloorHyperextension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeFlatBenchHyperextension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeReverseHyperextensionMachine),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeTBarRow),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSmithMachineGoodMorning),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeCablePullThrough),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeTwistingHyperextension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSwimming),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeFrogReverseHyperextension),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeBirdDog),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSeatedCableRopeRow),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeKettlebellDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeStandingToeTouches),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSeatedToeTouches),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeFoamRollerBackStretch),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeLyingUpperBodyRotation),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeStiffLegDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeKneelingBackRotation),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeBowPose),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeCatCowPose),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeKneelingTSpineRotation),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSupineSpinalTwist),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeLandmineTBarRow),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeBarbellPendlayRow),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSuperman),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeHinduPushUps),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeArmLegRaises),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellPullThrough),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeGluteHamRaise),
        context.resources.getStringArray(R.array.descriptionErectorSpinaePushUpWithRotation),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSidePlankRotation),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeKettlebellFigure8),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeBarbellSingleLegDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDumbbellSingleLegDeadlift),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeGoodMorningWithResistanceBand),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeRollingLikeABall),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeDhanurasanaRockingBowPose),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSwingGymstick),
        context.resources.getStringArray(R.array.descriptionErectorSpinaeSingleLegReverseHyperextensionGymstick),
    )
}